# Generated by Django 4.2.4 on 2023-08-29 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField(help_text='biograpgy of the consultant', max_length=1000)),
                ('expertise', models.CharField(help_text='expertise of the consultant', max_length=255)),
                ('available_visit_time', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='booked', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('sign_up_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('consultants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='consultation.consultantprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
